// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMlB7dSN8lsUPLMLoTT0PdVb_o1QWgG1o',
    appId: '1:171574447715:web:143391f8189f93e2f83256',
    messagingSenderId: '171574447715',
    projectId: 'dcproject-734d4',
    authDomain: 'dcproject-734d4.firebaseapp.com',
    storageBucket: 'dcproject-734d4.appspot.com',
    measurementId: 'G-X9C4B02440',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDapo0kkNRVkf5UzfrR6_GP8hbfGO2RIWY',
    appId: '1:171574447715:android:b8e1d0a20f00a322f83256',
    messagingSenderId: '171574447715',
    projectId: 'dcproject-734d4',
    storageBucket: 'dcproject-734d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPRo6-PkfE7aOHPTPeAVj9_UzaMvZml20',
    appId: '1:171574447715:ios:1388f2a4cb7fe0ebf83256',
    messagingSenderId: '171574447715',
    projectId: 'dcproject-734d4',
    storageBucket: 'dcproject-734d4.appspot.com',
    iosBundleId: 'com.example.gradtry4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPRo6-PkfE7aOHPTPeAVj9_UzaMvZml20',
    appId: '1:171574447715:ios:1388f2a4cb7fe0ebf83256',
    messagingSenderId: '171574447715',
    projectId: 'dcproject-734d4',
    storageBucket: 'dcproject-734d4.appspot.com',
    iosBundleId: 'com.example.gradtry4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMlB7dSN8lsUPLMLoTT0PdVb_o1QWgG1o',
    appId: '1:171574447715:web:0274e3e013dca0b7f83256',
    messagingSenderId: '171574447715',
    projectId: 'dcproject-734d4',
    authDomain: 'dcproject-734d4.firebaseapp.com',
    storageBucket: 'dcproject-734d4.appspot.com',
    measurementId: 'G-SMQJ36J1Z6',
  );
}
